### PR TITLE
add scrap tools

### PR DESCRIPTION
**Pull request by Skamiz**
adds the first two tools stages as described in my proposal which I put on discord

### CODE REVIEW

**Comment by Gerold55** [comment]
The reason we had it so you have to use a hatchet to get wood/trees is so players can't dig it using a hand and it gives it a slight real life aspect to it

**Comment by Skamiz** [comment]
Yes, but since I removed the odly_diggable_by_hand group from the wood nodes you can no longer dig them by hand at all.

**Comment by Gerold55** [comment]
I was wanting so if you even hit logs or wood by hand you can get hurt like in real life

**Comment by Skamiz** [comment]
Then we ould have to add the same functionality to every type of stone + overy other node which isn't diggabe by hand for it to make sense. If it is just for wood it makes the mechanic unsonsistent and unintuitive.

**Comment by Gerold55** [comment]
Well it was so you'd be turned away from chopping logs by hand... but ok :)

**Pull request merged**
