### PR TITLE
update wooden nodes

### PR DESCRIPTION
**Pull request by Skamiz**
Makes it so there are three wood types: dead, oak and balsa, each with a log, a stripped log and planks.
Plus a fourth type which only consists of planks. Which will be obtainable only from generated structures, according to my understanding.

woods

The IDs of the nodes have been changed to follow a uniform patern, which will break current schematics that use them, but since this is an alpha at best, I would like to see such iregularities eliminated as soon as possible, instead of draging them along and letting them propagate through the code for years, like in the case of tree node names in 'default'.

Node descriptions have also been updated to be unifom.

Texture names have been changed to reflect the new node IDs and two textures have been created for the dead tree type by copying and modifing the other wood textres.
I don't know how the 'dry oak' textures would fit in this schema so for now they are unused.

### CODE REVIEW

**Comment by Skamiz** [comment]
screenshot_20200409_183719
This is supposed to be the fourth kind of wood, right?
I will try to update the PR.

**Comment by theFox6** [comment]
Feel free to use any wood for the schematics that you think is appropriate.

**Comment by Skamiz** [comment]
I didn't make the schematic, I just accidentaly changed its wood type while changing the wood ids.

**Comment by theFox6** [comment]
Yes, I noticed

**Comment by Skamiz** [comment]
Just pushed the fix for that, can this be merged now?

**Pull request merged**
